version: '3.8'
services:
  redis:
    build: .
    image: redis:latest
    ports:
      - "6379:6379"

  redis-commander:
    build: .
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8001:8001"
    depends_on:
      - redis
  local-node:
    image: tonlabs/local-node
    ports:
      - "80:80"
    environment:
      USER_AGREEMENT: "yes"
    restart: always
